### ISSUE TITLE
Take advantage of the latest EDMCOverlay (installable)

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#151]
Instead of distributing a copy with EDR:
 - [ ] Update documentation to point folks to EDMCOverlay's MSI
 - [x] Update EDR to take advantage of the canonical EDMCOverlay
 - [x] Verify what happens when updating EDR (i.e. plugin specific EDMCOverlay present). Do things work?
 - [ ] Tell EDR users to upgrade EDMCOverlay if they still have the one that was included with EDR, keep things working though.
 - [x] When EDMCOVerlay is missing, use EDR's status line to guide folks (e.g. message + link to latest release)
 - [ ] Needs an updated release for canonical EDMCOverlay (with the send_shape method).

**Comment by lekeno** [comment]
Aiming at the next update to v0.8.x

**Comment by inorton** [comment]
Hmm odd, the new build doesn't actually have any code changes.  But occasionally directx or nvidia updates have made it unstable.

**Comment by inorton** [comment]
Can you find me your `edmcoverlay.log` file?

**Comment by lekeno** [comment]
Burned 0.8.3 for a hotfix so 0.8.4, hopefully.
@inorton I found it but it only had a few "connection forcibly closed" errors. I'll try to repro again and see if there is anything different.

**Comment by lekeno** [comment]
I see this error sometimes: "error in ensure_service: local variable 'program' referenced before assignment"

@inorton

**Comment by lekeno** [comment]
When closing EDMC, I'm also seeing this (probably minor):

```
error in send_raw: 'NoneType' object has no attribute 'send'
Traceback (most recent call last):
  File "plug.pyo", line 227, in notify_stop
  File "[...]\EDMarketConnector\plugins\EDMCOverlay\load.py", line 64, in plugin_stop
  File "[...]\EDMarketConnector\plugins\EDMCOverlay\edmcoverlay.py", line 109, in send_raw
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by lekeno** [comment]
I'm still block on the weird issues above but more importantly the canonical EDMCOverlay should include the send_shape method since EDR relies on it.

**Comment by incryptx** [comment]
I'm getting "error in ensure_service" when EDMC tries to run EDMCOverlay, which exits without starting.

Anyone know how to resolve this error?
