### ISSUE TITLE
Material trader feature may fail silently

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#218]
```
Traceback (most recent call last):
  File "threading.pyo", line 801, in __bootstrap_inner
  File "edrservicefinder.py", line 31, in run
  File "edrservicefinder.py", line 63, in nearby
  File "edrservicefinder.py", line 77, in __search
TypeError: 'NoneType' object is not iterable
```

**Comment by lekeno** [comment]
```
Traceback (most recent call last):
  File "threading.pyo", line 801, in __bootstrap_inner
  File "edrservicefinder.py", line 31, in run
  File "edrservicefinder.py", line 68, in nearby
  File "random.pyo", line 290, in shuffle
TypeError: object of type 'NoneType' has no len()
```
