### ISSUE TITLE
Search for Painite failed

### ISSUE THREAD

**Issue by lekeno** [lekeno/edr#285]
Conditions:
 - In Deciat
 - !search painite
```
Traceback (most recent call last):
  File "plug.pyo", line 305, in notify_journal_entry
  File "EDR\load.py", line 534, in journal_entry
  File "EDR\load.py", line 1122, in handle_commands
  File "EDR\load.py", line 1191, in handle_bang_commands
  File "EDR\edrclient.py", line 1673, in search_resource
  File "EDR\edrresourcefinder.py", line 185, in resource_near
  File "EDR\edrresourcefinder.py", line 667, in recommend_prospecting_ring
KeyError: 'ring' 
```

**Comment by lekeno** [comment]
Also HIP ... has the wrong ring.
